//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 测试项目.Mes_services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Mes_services.Web_services_MESSoap")]
    public interface Web_services_MESSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ZAFPO_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZAFPO", ReplyAction="*")]
        测试项目.Mes_services.InsertZAFPOResponse InsertZAFPO(测试项目.Mes_services.InsertZAFPORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZAFPO", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZAFPOResponse> InsertZAFPOAsync(测试项目.Mes_services.InsertZAFPORequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ZBTDATA_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZBTDATA", ReplyAction="*")]
        测试项目.Mes_services.InsertZBTDATAResponse InsertZBTDATA(测试项目.Mes_services.InsertZBTDATARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZBTDATA", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZBTDATAResponse> InsertZBTDATAAsync(测试项目.Mes_services.InsertZBTDATARequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ZCADMA_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZCADMA", ReplyAction="*")]
        测试项目.Mes_services.InsertZCADMAResponse InsertZCADMA(测试项目.Mes_services.InsertZCADMARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZCADMA", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZCADMAResponse> InsertZCADMAAsync(测试项目.Mes_services.InsertZCADMARequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ZCLSX_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZCLSX", ReplyAction="*")]
        测试项目.Mes_services.InsertZCLSXResponse InsertZCLSX(测试项目.Mes_services.InsertZCLSXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZCLSX", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZCLSXResponse> InsertZCLSXAsync(测试项目.Mes_services.InsertZCLSXRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ZMTMAUF_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZMTMAUF", ReplyAction="*")]
        测试项目.Mes_services.InsertZMTMAUFResponse InsertZMTMAUF(测试项目.Mes_services.InsertZMTMAUFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZMTMAUF", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZMTMAUFResponse> InsertZMTMAUFAsync(测试项目.Mes_services.InsertZMTMAUFRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ZMTMFILL_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZMTMFILL", ReplyAction="*")]
        测试项目.Mes_services.InsertZMTMFILLResponse InsertZMTMFILL(测试项目.Mes_services.InsertZMTMFILLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertZMTMFILL", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZMTMFILLResponse> InsertZMTMFILLAsync(测试项目.Mes_services.InsertZMTMFILLRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Tmp_ZTMTM_COMCTRL_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Tmp_ZTMTM_COMCTRL", ReplyAction="*")]
        测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLResponse Insert_Tmp_ZTMTM_COMCTRL(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Tmp_ZTMTM_COMCTRL", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLResponse> Insert_Tmp_ZTMTM_COMCTRLAsync(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Tmp_ZTMTM_COMOPT_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Tmp_ZTMTM_COMOPT", ReplyAction="*")]
        测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTResponse Insert_Tmp_ZTMTM_COMOPT(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Tmp_ZTMTM_COMOPT", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTResponse> Insert_Tmp_ZTMTM_COMOPTAsync(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Tmp_ZTMTM_COMREL_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Tmp_ZTMTM_COMRELT", ReplyAction="*")]
        测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTResponse Insert_Tmp_ZTMTM_COMRELT(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Tmp_ZTMTM_COMRELT", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTResponse> Insert_Tmp_ZTMTM_COMRELTAsync(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Tmp_PLMTOMES_XML 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_PLMTOMES", ReplyAction="*")]
        测试项目.Mes_services.Insert_PLMTOMESResponse Insert_PLMTOMES(测试项目.Mes_services.Insert_PLMTOMESRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_PLMTOMES", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.Insert_PLMTOMESResponse> Insert_PLMTOMESAsync(测试项目.Mes_services.Insert_PLMTOMESRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 s 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HELLOWORLD", ReplyAction="*")]
        测试项目.Mes_services.HELLOWORLDResponse HELLOWORLD(测试项目.Mes_services.HELLOWORLDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HELLOWORLD", ReplyAction="*")]
        System.Threading.Tasks.Task<测试项目.Mes_services.HELLOWORLDResponse> HELLOWORLDAsync(测试项目.Mes_services.HELLOWORLDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZAFPORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZAFPO", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZAFPORequestBody Body;
        
        public InsertZAFPORequest() {
        }
        
        public InsertZAFPORequest(测试项目.Mes_services.InsertZAFPORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZAFPORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZAFPO_XML;
        
        public InsertZAFPORequestBody() {
        }
        
        public InsertZAFPORequestBody(string ZAFPO_XML) {
            this.ZAFPO_XML = ZAFPO_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZAFPOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZAFPOResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZAFPOResponseBody Body;
        
        public InsertZAFPOResponse() {
        }
        
        public InsertZAFPOResponse(测试项目.Mes_services.InsertZAFPOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZAFPOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertZAFPOResult;
        
        public InsertZAFPOResponseBody() {
        }
        
        public InsertZAFPOResponseBody(bool InsertZAFPOResult) {
            this.InsertZAFPOResult = InsertZAFPOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZBTDATARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZBTDATA", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZBTDATARequestBody Body;
        
        public InsertZBTDATARequest() {
        }
        
        public InsertZBTDATARequest(测试项目.Mes_services.InsertZBTDATARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZBTDATARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZBTDATA_XML;
        
        public InsertZBTDATARequestBody() {
        }
        
        public InsertZBTDATARequestBody(string ZBTDATA_XML) {
            this.ZBTDATA_XML = ZBTDATA_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZBTDATAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZBTDATAResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZBTDATAResponseBody Body;
        
        public InsertZBTDATAResponse() {
        }
        
        public InsertZBTDATAResponse(测试项目.Mes_services.InsertZBTDATAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZBTDATAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertZBTDATAResult;
        
        public InsertZBTDATAResponseBody() {
        }
        
        public InsertZBTDATAResponseBody(bool InsertZBTDATAResult) {
            this.InsertZBTDATAResult = InsertZBTDATAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZCADMARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZCADMA", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZCADMARequestBody Body;
        
        public InsertZCADMARequest() {
        }
        
        public InsertZCADMARequest(测试项目.Mes_services.InsertZCADMARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZCADMARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZCADMA_XML;
        
        public InsertZCADMARequestBody() {
        }
        
        public InsertZCADMARequestBody(string ZCADMA_XML) {
            this.ZCADMA_XML = ZCADMA_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZCADMAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZCADMAResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZCADMAResponseBody Body;
        
        public InsertZCADMAResponse() {
        }
        
        public InsertZCADMAResponse(测试项目.Mes_services.InsertZCADMAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZCADMAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertZCADMAResult;
        
        public InsertZCADMAResponseBody() {
        }
        
        public InsertZCADMAResponseBody(bool InsertZCADMAResult) {
            this.InsertZCADMAResult = InsertZCADMAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZCLSXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZCLSX", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZCLSXRequestBody Body;
        
        public InsertZCLSXRequest() {
        }
        
        public InsertZCLSXRequest(测试项目.Mes_services.InsertZCLSXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZCLSXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZCLSX_XML;
        
        public InsertZCLSXRequestBody() {
        }
        
        public InsertZCLSXRequestBody(string ZCLSX_XML) {
            this.ZCLSX_XML = ZCLSX_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZCLSXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZCLSXResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZCLSXResponseBody Body;
        
        public InsertZCLSXResponse() {
        }
        
        public InsertZCLSXResponse(测试项目.Mes_services.InsertZCLSXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZCLSXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertZCLSXResult;
        
        public InsertZCLSXResponseBody() {
        }
        
        public InsertZCLSXResponseBody(bool InsertZCLSXResult) {
            this.InsertZCLSXResult = InsertZCLSXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZMTMAUFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZMTMAUF", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZMTMAUFRequestBody Body;
        
        public InsertZMTMAUFRequest() {
        }
        
        public InsertZMTMAUFRequest(测试项目.Mes_services.InsertZMTMAUFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZMTMAUFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZMTMAUF_XML;
        
        public InsertZMTMAUFRequestBody() {
        }
        
        public InsertZMTMAUFRequestBody(string ZMTMAUF_XML) {
            this.ZMTMAUF_XML = ZMTMAUF_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZMTMAUFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZMTMAUFResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZMTMAUFResponseBody Body;
        
        public InsertZMTMAUFResponse() {
        }
        
        public InsertZMTMAUFResponse(测试项目.Mes_services.InsertZMTMAUFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZMTMAUFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertZMTMAUFResult;
        
        public InsertZMTMAUFResponseBody() {
        }
        
        public InsertZMTMAUFResponseBody(bool InsertZMTMAUFResult) {
            this.InsertZMTMAUFResult = InsertZMTMAUFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZMTMFILLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZMTMFILL", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZMTMFILLRequestBody Body;
        
        public InsertZMTMFILLRequest() {
        }
        
        public InsertZMTMFILLRequest(测试项目.Mes_services.InsertZMTMFILLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZMTMFILLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZMTMFILL_XML;
        
        public InsertZMTMFILLRequestBody() {
        }
        
        public InsertZMTMFILLRequestBody(string ZMTMFILL_XML) {
            this.ZMTMFILL_XML = ZMTMFILL_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertZMTMFILLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertZMTMFILLResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.InsertZMTMFILLResponseBody Body;
        
        public InsertZMTMFILLResponse() {
        }
        
        public InsertZMTMFILLResponse(测试项目.Mes_services.InsertZMTMFILLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertZMTMFILLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertZMTMFILLResult;
        
        public InsertZMTMFILLResponseBody() {
        }
        
        public InsertZMTMFILLResponseBody(bool InsertZMTMFILLResult) {
            this.InsertZMTMFILLResult = InsertZMTMFILLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Tmp_ZTMTM_COMCTRLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Tmp_ZTMTM_COMCTRL", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequestBody Body;
        
        public Insert_Tmp_ZTMTM_COMCTRLRequest() {
        }
        
        public Insert_Tmp_ZTMTM_COMCTRLRequest(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Tmp_ZTMTM_COMCTRLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tmp_ZTMTM_COMCTRL_XML;
        
        public Insert_Tmp_ZTMTM_COMCTRLRequestBody() {
        }
        
        public Insert_Tmp_ZTMTM_COMCTRLRequestBody(string Tmp_ZTMTM_COMCTRL_XML) {
            this.Tmp_ZTMTM_COMCTRL_XML = Tmp_ZTMTM_COMCTRL_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Tmp_ZTMTM_COMCTRLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Tmp_ZTMTM_COMCTRLResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLResponseBody Body;
        
        public Insert_Tmp_ZTMTM_COMCTRLResponse() {
        }
        
        public Insert_Tmp_ZTMTM_COMCTRLResponse(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Tmp_ZTMTM_COMCTRLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Insert_Tmp_ZTMTM_COMCTRLResult;
        
        public Insert_Tmp_ZTMTM_COMCTRLResponseBody() {
        }
        
        public Insert_Tmp_ZTMTM_COMCTRLResponseBody(bool Insert_Tmp_ZTMTM_COMCTRLResult) {
            this.Insert_Tmp_ZTMTM_COMCTRLResult = Insert_Tmp_ZTMTM_COMCTRLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Tmp_ZTMTM_COMOPTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Tmp_ZTMTM_COMOPT", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequestBody Body;
        
        public Insert_Tmp_ZTMTM_COMOPTRequest() {
        }
        
        public Insert_Tmp_ZTMTM_COMOPTRequest(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Tmp_ZTMTM_COMOPTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tmp_ZTMTM_COMOPT_XML;
        
        public Insert_Tmp_ZTMTM_COMOPTRequestBody() {
        }
        
        public Insert_Tmp_ZTMTM_COMOPTRequestBody(string Tmp_ZTMTM_COMOPT_XML) {
            this.Tmp_ZTMTM_COMOPT_XML = Tmp_ZTMTM_COMOPT_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Tmp_ZTMTM_COMOPTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Tmp_ZTMTM_COMOPTResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTResponseBody Body;
        
        public Insert_Tmp_ZTMTM_COMOPTResponse() {
        }
        
        public Insert_Tmp_ZTMTM_COMOPTResponse(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Tmp_ZTMTM_COMOPTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Insert_Tmp_ZTMTM_COMOPTResult;
        
        public Insert_Tmp_ZTMTM_COMOPTResponseBody() {
        }
        
        public Insert_Tmp_ZTMTM_COMOPTResponseBody(bool Insert_Tmp_ZTMTM_COMOPTResult) {
            this.Insert_Tmp_ZTMTM_COMOPTResult = Insert_Tmp_ZTMTM_COMOPTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Tmp_ZTMTM_COMRELTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Tmp_ZTMTM_COMRELT", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequestBody Body;
        
        public Insert_Tmp_ZTMTM_COMRELTRequest() {
        }
        
        public Insert_Tmp_ZTMTM_COMRELTRequest(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Tmp_ZTMTM_COMRELTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tmp_ZTMTM_COMREL_XML;
        
        public Insert_Tmp_ZTMTM_COMRELTRequestBody() {
        }
        
        public Insert_Tmp_ZTMTM_COMRELTRequestBody(string Tmp_ZTMTM_COMREL_XML) {
            this.Tmp_ZTMTM_COMREL_XML = Tmp_ZTMTM_COMREL_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Tmp_ZTMTM_COMRELTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Tmp_ZTMTM_COMRELTResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTResponseBody Body;
        
        public Insert_Tmp_ZTMTM_COMRELTResponse() {
        }
        
        public Insert_Tmp_ZTMTM_COMRELTResponse(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Tmp_ZTMTM_COMRELTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Insert_Tmp_ZTMTM_COMRELTResult;
        
        public Insert_Tmp_ZTMTM_COMRELTResponseBody() {
        }
        
        public Insert_Tmp_ZTMTM_COMRELTResponseBody(bool Insert_Tmp_ZTMTM_COMRELTResult) {
            this.Insert_Tmp_ZTMTM_COMRELTResult = Insert_Tmp_ZTMTM_COMRELTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_PLMTOMESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_PLMTOMES", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.Insert_PLMTOMESRequestBody Body;
        
        public Insert_PLMTOMESRequest() {
        }
        
        public Insert_PLMTOMESRequest(测试项目.Mes_services.Insert_PLMTOMESRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_PLMTOMESRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tmp_PLMTOMES_XML;
        
        public Insert_PLMTOMESRequestBody() {
        }
        
        public Insert_PLMTOMESRequestBody(string Tmp_PLMTOMES_XML) {
            this.Tmp_PLMTOMES_XML = Tmp_PLMTOMES_XML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_PLMTOMESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_PLMTOMESResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.Insert_PLMTOMESResponseBody Body;
        
        public Insert_PLMTOMESResponse() {
        }
        
        public Insert_PLMTOMESResponse(测试项目.Mes_services.Insert_PLMTOMESResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_PLMTOMESResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Insert_PLMTOMESResult;
        
        public Insert_PLMTOMESResponseBody() {
        }
        
        public Insert_PLMTOMESResponseBody(bool Insert_PLMTOMESResult) {
            this.Insert_PLMTOMESResult = Insert_PLMTOMESResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HELLOWORLDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HELLOWORLD", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.HELLOWORLDRequestBody Body;
        
        public HELLOWORLDRequest() {
        }
        
        public HELLOWORLDRequest(测试项目.Mes_services.HELLOWORLDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HELLOWORLDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public HELLOWORLDRequestBody() {
        }
        
        public HELLOWORLDRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HELLOWORLDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HELLOWORLDResponse", Namespace="http://tempuri.org/", Order=0)]
        public 测试项目.Mes_services.HELLOWORLDResponseBody Body;
        
        public HELLOWORLDResponse() {
        }
        
        public HELLOWORLDResponse(测试项目.Mes_services.HELLOWORLDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HELLOWORLDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HELLOWORLDResult;
        
        public HELLOWORLDResponseBody() {
        }
        
        public HELLOWORLDResponseBody(string HELLOWORLDResult) {
            this.HELLOWORLDResult = HELLOWORLDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Web_services_MESSoapChannel : 测试项目.Mes_services.Web_services_MESSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Web_services_MESSoapClient : System.ServiceModel.ClientBase<测试项目.Mes_services.Web_services_MESSoap>, 测试项目.Mes_services.Web_services_MESSoap {
        
        public Web_services_MESSoapClient() {
        }
        
        public Web_services_MESSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Web_services_MESSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Web_services_MESSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Web_services_MESSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.InsertZAFPOResponse 测试项目.Mes_services.Web_services_MESSoap.InsertZAFPO(测试项目.Mes_services.InsertZAFPORequest request) {
            return base.Channel.InsertZAFPO(request);
        }
        
        public bool InsertZAFPO(string ZAFPO_XML) {
            测试项目.Mes_services.InsertZAFPORequest inValue = new 测试项目.Mes_services.InsertZAFPORequest();
            inValue.Body = new 测试项目.Mes_services.InsertZAFPORequestBody();
            inValue.Body.ZAFPO_XML = ZAFPO_XML;
            测试项目.Mes_services.InsertZAFPOResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZAFPO(inValue);
            return retVal.Body.InsertZAFPOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZAFPOResponse> 测试项目.Mes_services.Web_services_MESSoap.InsertZAFPOAsync(测试项目.Mes_services.InsertZAFPORequest request) {
            return base.Channel.InsertZAFPOAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.InsertZAFPOResponse> InsertZAFPOAsync(string ZAFPO_XML) {
            测试项目.Mes_services.InsertZAFPORequest inValue = new 测试项目.Mes_services.InsertZAFPORequest();
            inValue.Body = new 测试项目.Mes_services.InsertZAFPORequestBody();
            inValue.Body.ZAFPO_XML = ZAFPO_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZAFPOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.InsertZBTDATAResponse 测试项目.Mes_services.Web_services_MESSoap.InsertZBTDATA(测试项目.Mes_services.InsertZBTDATARequest request) {
            return base.Channel.InsertZBTDATA(request);
        }
        
        public bool InsertZBTDATA(string ZBTDATA_XML) {
            测试项目.Mes_services.InsertZBTDATARequest inValue = new 测试项目.Mes_services.InsertZBTDATARequest();
            inValue.Body = new 测试项目.Mes_services.InsertZBTDATARequestBody();
            inValue.Body.ZBTDATA_XML = ZBTDATA_XML;
            测试项目.Mes_services.InsertZBTDATAResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZBTDATA(inValue);
            return retVal.Body.InsertZBTDATAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZBTDATAResponse> 测试项目.Mes_services.Web_services_MESSoap.InsertZBTDATAAsync(测试项目.Mes_services.InsertZBTDATARequest request) {
            return base.Channel.InsertZBTDATAAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.InsertZBTDATAResponse> InsertZBTDATAAsync(string ZBTDATA_XML) {
            测试项目.Mes_services.InsertZBTDATARequest inValue = new 测试项目.Mes_services.InsertZBTDATARequest();
            inValue.Body = new 测试项目.Mes_services.InsertZBTDATARequestBody();
            inValue.Body.ZBTDATA_XML = ZBTDATA_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZBTDATAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.InsertZCADMAResponse 测试项目.Mes_services.Web_services_MESSoap.InsertZCADMA(测试项目.Mes_services.InsertZCADMARequest request) {
            return base.Channel.InsertZCADMA(request);
        }
        
        public bool InsertZCADMA(string ZCADMA_XML) {
            测试项目.Mes_services.InsertZCADMARequest inValue = new 测试项目.Mes_services.InsertZCADMARequest();
            inValue.Body = new 测试项目.Mes_services.InsertZCADMARequestBody();
            inValue.Body.ZCADMA_XML = ZCADMA_XML;
            测试项目.Mes_services.InsertZCADMAResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZCADMA(inValue);
            return retVal.Body.InsertZCADMAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZCADMAResponse> 测试项目.Mes_services.Web_services_MESSoap.InsertZCADMAAsync(测试项目.Mes_services.InsertZCADMARequest request) {
            return base.Channel.InsertZCADMAAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.InsertZCADMAResponse> InsertZCADMAAsync(string ZCADMA_XML) {
            测试项目.Mes_services.InsertZCADMARequest inValue = new 测试项目.Mes_services.InsertZCADMARequest();
            inValue.Body = new 测试项目.Mes_services.InsertZCADMARequestBody();
            inValue.Body.ZCADMA_XML = ZCADMA_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZCADMAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.InsertZCLSXResponse 测试项目.Mes_services.Web_services_MESSoap.InsertZCLSX(测试项目.Mes_services.InsertZCLSXRequest request) {
            return base.Channel.InsertZCLSX(request);
        }
        
        public bool InsertZCLSX(string ZCLSX_XML) {
            测试项目.Mes_services.InsertZCLSXRequest inValue = new 测试项目.Mes_services.InsertZCLSXRequest();
            inValue.Body = new 测试项目.Mes_services.InsertZCLSXRequestBody();
            inValue.Body.ZCLSX_XML = ZCLSX_XML;
            测试项目.Mes_services.InsertZCLSXResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZCLSX(inValue);
            return retVal.Body.InsertZCLSXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZCLSXResponse> 测试项目.Mes_services.Web_services_MESSoap.InsertZCLSXAsync(测试项目.Mes_services.InsertZCLSXRequest request) {
            return base.Channel.InsertZCLSXAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.InsertZCLSXResponse> InsertZCLSXAsync(string ZCLSX_XML) {
            测试项目.Mes_services.InsertZCLSXRequest inValue = new 测试项目.Mes_services.InsertZCLSXRequest();
            inValue.Body = new 测试项目.Mes_services.InsertZCLSXRequestBody();
            inValue.Body.ZCLSX_XML = ZCLSX_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZCLSXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.InsertZMTMAUFResponse 测试项目.Mes_services.Web_services_MESSoap.InsertZMTMAUF(测试项目.Mes_services.InsertZMTMAUFRequest request) {
            return base.Channel.InsertZMTMAUF(request);
        }
        
        public bool InsertZMTMAUF(string ZMTMAUF_XML) {
            测试项目.Mes_services.InsertZMTMAUFRequest inValue = new 测试项目.Mes_services.InsertZMTMAUFRequest();
            inValue.Body = new 测试项目.Mes_services.InsertZMTMAUFRequestBody();
            inValue.Body.ZMTMAUF_XML = ZMTMAUF_XML;
            测试项目.Mes_services.InsertZMTMAUFResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZMTMAUF(inValue);
            return retVal.Body.InsertZMTMAUFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZMTMAUFResponse> 测试项目.Mes_services.Web_services_MESSoap.InsertZMTMAUFAsync(测试项目.Mes_services.InsertZMTMAUFRequest request) {
            return base.Channel.InsertZMTMAUFAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.InsertZMTMAUFResponse> InsertZMTMAUFAsync(string ZMTMAUF_XML) {
            测试项目.Mes_services.InsertZMTMAUFRequest inValue = new 测试项目.Mes_services.InsertZMTMAUFRequest();
            inValue.Body = new 测试项目.Mes_services.InsertZMTMAUFRequestBody();
            inValue.Body.ZMTMAUF_XML = ZMTMAUF_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZMTMAUFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.InsertZMTMFILLResponse 测试项目.Mes_services.Web_services_MESSoap.InsertZMTMFILL(测试项目.Mes_services.InsertZMTMFILLRequest request) {
            return base.Channel.InsertZMTMFILL(request);
        }
        
        public bool InsertZMTMFILL(string ZMTMFILL_XML) {
            测试项目.Mes_services.InsertZMTMFILLRequest inValue = new 测试项目.Mes_services.InsertZMTMFILLRequest();
            inValue.Body = new 测试项目.Mes_services.InsertZMTMFILLRequestBody();
            inValue.Body.ZMTMFILL_XML = ZMTMFILL_XML;
            测试项目.Mes_services.InsertZMTMFILLResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZMTMFILL(inValue);
            return retVal.Body.InsertZMTMFILLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.InsertZMTMFILLResponse> 测试项目.Mes_services.Web_services_MESSoap.InsertZMTMFILLAsync(测试项目.Mes_services.InsertZMTMFILLRequest request) {
            return base.Channel.InsertZMTMFILLAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.InsertZMTMFILLResponse> InsertZMTMFILLAsync(string ZMTMFILL_XML) {
            测试项目.Mes_services.InsertZMTMFILLRequest inValue = new 测试项目.Mes_services.InsertZMTMFILLRequest();
            inValue.Body = new 测试项目.Mes_services.InsertZMTMFILLRequestBody();
            inValue.Body.ZMTMFILL_XML = ZMTMFILL_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).InsertZMTMFILLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLResponse 测试项目.Mes_services.Web_services_MESSoap.Insert_Tmp_ZTMTM_COMCTRL(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequest request) {
            return base.Channel.Insert_Tmp_ZTMTM_COMCTRL(request);
        }
        
        public bool Insert_Tmp_ZTMTM_COMCTRL(string Tmp_ZTMTM_COMCTRL_XML) {
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequest inValue = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequest();
            inValue.Body = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequestBody();
            inValue.Body.Tmp_ZTMTM_COMCTRL_XML = Tmp_ZTMTM_COMCTRL_XML;
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).Insert_Tmp_ZTMTM_COMCTRL(inValue);
            return retVal.Body.Insert_Tmp_ZTMTM_COMCTRLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLResponse> 测试项目.Mes_services.Web_services_MESSoap.Insert_Tmp_ZTMTM_COMCTRLAsync(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequest request) {
            return base.Channel.Insert_Tmp_ZTMTM_COMCTRLAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLResponse> Insert_Tmp_ZTMTM_COMCTRLAsync(string Tmp_ZTMTM_COMCTRL_XML) {
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequest inValue = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequest();
            inValue.Body = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMCTRLRequestBody();
            inValue.Body.Tmp_ZTMTM_COMCTRL_XML = Tmp_ZTMTM_COMCTRL_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).Insert_Tmp_ZTMTM_COMCTRLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTResponse 测试项目.Mes_services.Web_services_MESSoap.Insert_Tmp_ZTMTM_COMOPT(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequest request) {
            return base.Channel.Insert_Tmp_ZTMTM_COMOPT(request);
        }
        
        public bool Insert_Tmp_ZTMTM_COMOPT(string Tmp_ZTMTM_COMOPT_XML) {
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequest inValue = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequest();
            inValue.Body = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequestBody();
            inValue.Body.Tmp_ZTMTM_COMOPT_XML = Tmp_ZTMTM_COMOPT_XML;
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).Insert_Tmp_ZTMTM_COMOPT(inValue);
            return retVal.Body.Insert_Tmp_ZTMTM_COMOPTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTResponse> 测试项目.Mes_services.Web_services_MESSoap.Insert_Tmp_ZTMTM_COMOPTAsync(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequest request) {
            return base.Channel.Insert_Tmp_ZTMTM_COMOPTAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTResponse> Insert_Tmp_ZTMTM_COMOPTAsync(string Tmp_ZTMTM_COMOPT_XML) {
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequest inValue = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequest();
            inValue.Body = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMOPTRequestBody();
            inValue.Body.Tmp_ZTMTM_COMOPT_XML = Tmp_ZTMTM_COMOPT_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).Insert_Tmp_ZTMTM_COMOPTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTResponse 测试项目.Mes_services.Web_services_MESSoap.Insert_Tmp_ZTMTM_COMRELT(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequest request) {
            return base.Channel.Insert_Tmp_ZTMTM_COMRELT(request);
        }
        
        public bool Insert_Tmp_ZTMTM_COMRELT(string Tmp_ZTMTM_COMREL_XML) {
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequest inValue = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequest();
            inValue.Body = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequestBody();
            inValue.Body.Tmp_ZTMTM_COMREL_XML = Tmp_ZTMTM_COMREL_XML;
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).Insert_Tmp_ZTMTM_COMRELT(inValue);
            return retVal.Body.Insert_Tmp_ZTMTM_COMRELTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTResponse> 测试项目.Mes_services.Web_services_MESSoap.Insert_Tmp_ZTMTM_COMRELTAsync(测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequest request) {
            return base.Channel.Insert_Tmp_ZTMTM_COMRELTAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTResponse> Insert_Tmp_ZTMTM_COMRELTAsync(string Tmp_ZTMTM_COMREL_XML) {
            测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequest inValue = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequest();
            inValue.Body = new 测试项目.Mes_services.Insert_Tmp_ZTMTM_COMRELTRequestBody();
            inValue.Body.Tmp_ZTMTM_COMREL_XML = Tmp_ZTMTM_COMREL_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).Insert_Tmp_ZTMTM_COMRELTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.Insert_PLMTOMESResponse 测试项目.Mes_services.Web_services_MESSoap.Insert_PLMTOMES(测试项目.Mes_services.Insert_PLMTOMESRequest request) {
            return base.Channel.Insert_PLMTOMES(request);
        }
        
        public bool Insert_PLMTOMES(string Tmp_PLMTOMES_XML) {
            测试项目.Mes_services.Insert_PLMTOMESRequest inValue = new 测试项目.Mes_services.Insert_PLMTOMESRequest();
            inValue.Body = new 测试项目.Mes_services.Insert_PLMTOMESRequestBody();
            inValue.Body.Tmp_PLMTOMES_XML = Tmp_PLMTOMES_XML;
            测试项目.Mes_services.Insert_PLMTOMESResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).Insert_PLMTOMES(inValue);
            return retVal.Body.Insert_PLMTOMESResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.Insert_PLMTOMESResponse> 测试项目.Mes_services.Web_services_MESSoap.Insert_PLMTOMESAsync(测试项目.Mes_services.Insert_PLMTOMESRequest request) {
            return base.Channel.Insert_PLMTOMESAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.Insert_PLMTOMESResponse> Insert_PLMTOMESAsync(string Tmp_PLMTOMES_XML) {
            测试项目.Mes_services.Insert_PLMTOMESRequest inValue = new 测试项目.Mes_services.Insert_PLMTOMESRequest();
            inValue.Body = new 测试项目.Mes_services.Insert_PLMTOMESRequestBody();
            inValue.Body.Tmp_PLMTOMES_XML = Tmp_PLMTOMES_XML;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).Insert_PLMTOMESAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        测试项目.Mes_services.HELLOWORLDResponse 测试项目.Mes_services.Web_services_MESSoap.HELLOWORLD(测试项目.Mes_services.HELLOWORLDRequest request) {
            return base.Channel.HELLOWORLD(request);
        }
        
        public string HELLOWORLD(string s) {
            测试项目.Mes_services.HELLOWORLDRequest inValue = new 测试项目.Mes_services.HELLOWORLDRequest();
            inValue.Body = new 测试项目.Mes_services.HELLOWORLDRequestBody();
            inValue.Body.s = s;
            测试项目.Mes_services.HELLOWORLDResponse retVal = ((测试项目.Mes_services.Web_services_MESSoap)(this)).HELLOWORLD(inValue);
            return retVal.Body.HELLOWORLDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<测试项目.Mes_services.HELLOWORLDResponse> 测试项目.Mes_services.Web_services_MESSoap.HELLOWORLDAsync(测试项目.Mes_services.HELLOWORLDRequest request) {
            return base.Channel.HELLOWORLDAsync(request);
        }
        
        public System.Threading.Tasks.Task<测试项目.Mes_services.HELLOWORLDResponse> HELLOWORLDAsync(string s) {
            测试项目.Mes_services.HELLOWORLDRequest inValue = new 测试项目.Mes_services.HELLOWORLDRequest();
            inValue.Body = new 测试项目.Mes_services.HELLOWORLDRequestBody();
            inValue.Body.s = s;
            return ((测试项目.Mes_services.Web_services_MESSoap)(this)).HELLOWORLDAsync(inValue);
        }
    }
}
